### ISSUE TITLE
Crash on Android when biometric verification failed

### ISSUE THREAD

**Issue by danielzq** [salkuadrat/BiometricX#1]
version: biometricx 0.0.2
flutter 2.5.3 stable
`   
 java.lang.IllegalStateException: Reply already submitted
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:164)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:243)
        at com.salkuadrat.biometricx.BiometricxPlugin.failed(BiometricxPlugin.kt:222)
        at com.salkuadrat.biometricx.BiometricxPlugin.access$failed(BiometricxPlugin.kt:22)
        at com.salkuadrat.biometricx.BiometricxPlugin$encrypt$3.invoke(BiometricxPlugin.kt:152)
        at com.salkuadrat.biometricx.BiometricxPlugin$encrypt$3.invoke(BiometricxPlugin.kt:22)
        at com.salkuadrat.biometricx.BiometricHelper$authenticationCallback$1.onAuthenticationFailed(BiometricHelper.kt:205)
        at androidx.biometric.BiometricFragment$11.run(BiometricFragment.java:955)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:205)
        at android.app.ActivityThread.main(ActivityThread.java:6991)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
`

**Comment by maulanauls** [comment]
same here 
E/AndroidRuntime( 8990): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 8990): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
E/AndroidRuntime( 8990): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:272)
E/AndroidRuntime( 8990): 	at com.salkuadrat.biometricx.BiometricxPlugin.failed(BiometricxPlugin.kt:222)
E/AndroidRuntime( 8990): 	at com.salkuadrat.biometricx.BiometricxPlugin.access$failed(BiometricxPlugin.kt:22)
E/AndroidRuntime( 8990): 	at com.salkuadrat.biometricx.BiometricxPlugin$encrypt$3.invoke(BiometricxPlugin.kt:152)
E/AndroidRuntime( 8990): 	at com.salkuadrat.biometricx.BiometricxPlugin$encrypt$3.invoke(BiometricxPlugin.kt:115)
E/AndroidRuntime( 8990): 	at com.salkuadrat.biometricx.BiometricHelper$authenticationCallback$1.onAuthenticationFailed(BiometricHelper.kt:205)
E/AndroidRuntime( 8990): 	at androidx.biometric.BiometricFragment$11.run(BiometricFragment.java:955)
E/AndroidRuntime( 8990): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 8990): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 8990): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime( 8990): 	at android.app.ActivityThread.main(ActivityThread.java:8034)
E/AndroidRuntime( 8990): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8990): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 8990): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
